### ISSUE TITLE
[Feature request] Add permission control

### ISSUE THREAD

**Issue by michalgrudzien** [FriendsOfFlarum/pages#13]
It would be great to have control over user's access to a certain page. Right now it's impossible to create a page for "users only" and keep it unavailable for guests.
Ideally extension could provide setting permissions to a page for user groups - this would eliminate guest access and also provide much more flexibility (f.e. 'moderator only' pages).

**Comment by clarkwinkelmann** [comment]
Version 0.3.0 #14 introduces restricted pages.

Pages are either restricted or not restricted, and who can access restricted pages is a global setting.

I'll close this issue for now, let us know what you think of the new feature :smiley:

**Comment by michalgrudzien** [comment]
Checked it quickly and it works like a charm! Thank you very much for answering this request!!!

**Comment by clarkwinkelmann** [comment]
It was actually sponsored by a client :hugs:
