### ISSUE TITLE
Page title issue on admin area

### ISSUE THREAD

**Issue by tolgaaaltas** [FriendsOfFlarum/pages#15]
When I visited the Pages tab in the Admin area, I saw "0" at the end of each page title. 

Example:
Page title: Text
Shown as: Text0

![Example](https://i.ibb.co/CnvRGgh/Screenshot-20200229-115100-01.png)

**Comment by dsevillamartin** [comment]
I'm assuming it is because of https://github.com/FriendsOfFlarum/pages/blob/145fbb126ff34adcabb4d7e0acd3d31e93b0047d/js/src/admin/components/PagesListItem.js#L23.

**Comment by clarkwinkelmann** [comment]
I was so sure that `&&` idea was going to come biting us back. Should have gone for `? [...] : null`

(if `length` is falsy but not an empty string, null or undefined, the return value of the condition will be rendered by Mithril)

Javascript boolean operations are so fantastic.

**Comment by dsevillamartin** [comment]
FYI this could have been fixed with `!!badges.length` as well. That way it wouldn't render `false`.
