### ISSUE TITLE
The content may not be greater than 65535 characters

### ISSUE THREAD

**Issue by rafaucau** [FriendsOfFlarum/pages#22]
When I try to add a large page I get this error: `The content may not be greater than 65535 characters.`
What is this limit for? It would be nice if the number of characters was unlimited.

**Comment by rafaucau** [comment]
> What is this limit for?

Ok, I found it: https://github.com/FriendsOfFlarum/pages/blob/master/migrations/2016_04_11_182821__create_pages_table.php#L28
Just change to longText and it will be fine

**Comment by clarkwinkelmann** [comment]
I'm not sure **why** we chose `TEXT` for the database type, but that's indeed the reason we have that limit.

I'm not sure what we should adopt. Flarum does use `MEDIUMTEXT` for the post content, so this seems like a good choice .

**Comment by rafaucau** [comment]
I believe that TEXT is not enough and it is very important to change to MEDIUMTEXT. The content of the page is usually longer than the post. The problem occurred when I was trying to create a privacy policy page.

I guess there is no other option than migration. Every plugin uses migrations and it's normal to type `php flarum migrate` after upgrading.
