### ISSUE TITLE
FOF Pages dosent follow the HTML Code.

### ISSUE THREAD

**Issue by shawny43** [FriendsOfFlarum/pages#36]
## Bug Report

**Current Behavior**
Want to add outlook into the forum but doesn't follow the code i wanted to.

**Steps to Reproduce**
1. Go to Admin Settings.
2. Go to FOF Pages
3. Click Add page
4. Add code and others informations.
5. Check HTML Support.
6. Test it and we still not able to size the iframe.

**Expected Behavior**
Adding an iFrame with a specific size doesn't follow and lock to the size. Impossible to adjust whats we wanted.

Here a simple code: 
`<iframe src="https://outlook.live.com/owa/calendar/00000000-0000-0000-0000-000000000000/da18d3fe-5675-4b7f-95d6-2739a0214b74/cid-15E030418AC10077/index.html" style="width: 1000px; height: 600px;"></iframe>`

**Screenshots**
https://imgur.com/a/zuwqUT4

**Environment**
- Flarum version: FreeFlarum - BUILD 16
- Extension version: 0.7.0
- Website URL: https://shawny43.flarum.cloud
- Webserver: FreeFlarum
- Hosting environment: FreeFlarum
- PHP version: Unknown (Only FreeFlarum know.)
- Browser: Edge Chromium - Version 91.0.864.54 (Version official) (64 bits)

```
Output of "php flarum info", run this in terminal in your Flarum directory.

Only FreeFlarum can have access.
```

**Possible solution(s)**

**Additional Context**
Can't update or install by myself if all extensions was managed by FreeFlarum by proof (Subdomain.Flarum.cloud). I can't install or update at all.

**Comment by dsevillamartin** [comment]
This extension does pass the entire HTML code.

![image](https://user-images.githubusercontent.com/6401250/122922093-45a17700-d331-11eb-89b9-671a00ba9719.png)


The issue you're encountering is that the parent container classes have fixed widths - you should be able to solve this using a stylesheet alongside the iframe code.

**Comment by shawny43** [comment]
Okay and how i can do that from CSS?

**Comment by dsevillamartin** [comment]
I recommend putting this in a <style> tag in the page html. Replace `100vw` with your desired width, and add margins if you want.


```css
.Pages-container.container {
  max-width: 100vw;
  width: 100vw;
}

.Pages-container iframe {
  width: 100%;
}
```
