### ISSUE TITLE
Mentions in page content are not working: `@"[deleted]"#123`

### ISSUE THREAD

**Issue by iPurpl3x** [FriendsOfFlarum/pages#39]
## Bug Report

**Current Behavior**
When doing a @mention in a page content (I tried that with HTML activated) it renders as `@"[deleted]"#123`.

**Expected Behavior**
Either show a normal mention like in a post or show the raw content that has been provided.

**Environment**
- Flarum version: 1.0.4
- Extension version: 1.0.1
- Website URL: https://community.upc.ch/
- PHP version: 8.0.12

**Comment by dsevillamartin** [comment]
See https://github.com/flarum/core/issues/2902.

**Comment by dsevillamartin** [comment]
Fixed in Flarum v1.2.0. Mentions will not work in HTML mode as that code does not go through the formatter.
