### ISSUE TITLE
Add as home button

### ISSUE THREAD

**Issue by milkbump** [FriendsOfFlarum/pages#4]
Currently when you click the add homepage option, it disables the set home button if it's already set as home page. But this doesn't give you the option to remove from homepage.

Expected behaviour: When you click the as homepage button, it adds to homepage and if it's already homepage button, disables it from being homepage.

**Comment by dsevillamartin** [comment]
@kwangure To stop it from being the homepage, you can go to the "Basics" page in the admin dashboard and change the "Home Page" setting.

**Comment by milkbump** [comment]
Noted. This is not immediately obvious though. In a future iteration of the extension, perhaps consider adding the feature to disable the page from the "Pages" tab, or simply add a note somewhere on the page that the homepage is disabled from the "Basics" page.
