### ISSUE TITLE
Markdown spacing is incorrect

### ISSUE THREAD

**Issue by katosdev** [FriendsOfFlarum/pages#7]
When using markdown with FoF Pages, there is additional spacing that is entered which does not match throughout the site, so some spaces are larger than others.
Tested using Header 1, 2, and lists.

Example: 
https://i.imgur.com/qV69LVO.png

Link to discussion:
https://discuss.flarum.org/d/18301-friendsofflarum-pages/110

**Comment by luceos** [comment]
This is caused by the css/styling of the forum, they are called margin and padding. You can influence these by using the native Flarum custom css functionality in the admin. Elements to target are `h1, h2, h3, h4` and `ul` for list margins.

This is not a responsibility of this extension.
